/**
 * Content Version Error Enum
 * Error codes for version history operations
 */

export enum ContentVersionError {
  // Validation errors (400)
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_CONTENT = 'INVALID_CONTENT',
  INVALID_CONTENT_ID = 'INVALID_CONTENT_ID',
  INVALID_VERSION_NUMBER = 'INVALID_VERSION_NUMBER',
  INVALID_VERSION_RANGE = 'INVALID_VERSION_RANGE',

  // Not found errors (404)
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  OLD_VERSION_NOT_FOUND = 'OLD_VERSION_NOT_FOUND',
  NEW_VERSION_NOT_FOUND = 'NEW_VERSION_NOT_FOUND',

  // Conflict errors (409)
  VERSION_ALREADY_EXISTS = 'VERSION_ALREADY_EXISTS',
  CANNOT_RESTORE_CURRENT_VERSION = 'CANNOT_RESTORE_CURRENT_VERSION',
  CANNOT_RESTORE_ARCHIVED_CONTENT = 'CANNOT_RESTORE_ARCHIVED_CONTENT',
  VERSION_ALREADY_CURRENT = 'VERSION_ALREADY_CURRENT',
  CANNOT_COMPARE_SAME_VERSION = 'CANNOT_COMPARE_SAME_VERSION',

  // Server errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
