/**
 * Payment Application Errors
 * Error enums for payment, subscription, and coupon operations
 */

/**
 * Payment Tier Errors
 */
export enum PaymentTierError {
  TIER_NOT_FOUND = 'TIER_NOT_FOUND',
  MAX_TIERS_REACHED = 'MAX_TIERS_REACHED', // V1: 2 tiers max (1 free + 1 paid)
  TIER_NOT_ACTIVE = 'TIER_NOT_ACTIVE',
  INVALID_PRICE = 'INVALID_PRICE',
  STRIPE_ERROR = 'STRIPE_ERROR',
  COMMUNITY_NOT_FOUND = 'COMMUNITY_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_INPUT = 'INVALID_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

/**
 * Subscription Errors
 */
export enum SubscriptionError {
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  ALREADY_SUBSCRIBED = 'ALREADY_SUBSCRIBED',
  TIER_NOT_FOUND = 'TIER_NOT_FOUND',
  TIER_NOT_ACTIVE = 'TIER_NOT_ACTIVE',
  STRIPE_ERROR = 'STRIPE_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_INPUT = 'INVALID_INPUT',
  CHECKOUT_FAILED = 'CHECKOUT_FAILED',
  WEBHOOK_PROCESSING_FAILED = 'WEBHOOK_PROCESSING_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

/**
 * Coupon Errors
 */
export enum CouponError {
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_INACTIVE = 'COUPON_INACTIVE',
  MAX_USES_REACHED = 'MAX_USES_REACHED',
  INVALID_CODE = 'INVALID_CODE',
  STRIPE_ERROR = 'STRIPE_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_INPUT = 'INVALID_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

/**
 * Checkout Errors
 */
export enum CheckoutError {
  TIER_NOT_FOUND = 'TIER_NOT_FOUND',
  TIER_NOT_ACTIVE = 'TIER_NOT_ACTIVE',
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_INVALID = 'COUPON_INVALID',
  INVALID_INPUT = 'INVALID_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

/**
 * Access Control Errors
 */
export enum AccessError {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  NO_ACTIVE_SUBSCRIPTION = 'NO_ACTIVE_SUBSCRIPTION',
  TIER_REQUIRED = 'TIER_REQUIRED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
